### ISSUE TITLE
[Question] Are there going to be any customizable options?

### ISSUE THREAD

**Issue by MostHated** [levelrin/dart-stylerin#38]
Hey there, 
    Searching for options other than dartfmt lead me to this project, I was wondering if there were any plans to have any sort of customizable options?

One example would be, I hate when I have something like this below:
```dart
  TextEditingController get firstCtrl => _firstCtrl;
  TextEditingController get lastCtrl => _lastCtrl;
  TextEditingController get serialNum => _serialNum;
  TextEditingController get contactEmail => _contactEmail;
  User get user => _user;
```
Then it ends up becoming this:
```dart
  TextEditingController get firstCtrl => _firstCtrl;

  TextEditingController get lastCtrl => _lastCtrl;

  TextEditingController get serialNum => _serialNum;

  TextEditingController get contactEmail => _contactEmail;

  User get user => _user;
```
Some things it makes multiline, that I would just like it to stay single line, but also vice versa, such as I would love to see is an option to force ternary operators to be multiline such as, I would like for it to stay like this:
```dart
    (auth.isSignedIn) 
        ? silentLoginEvent() 
        : log.i('Firebase instance created. Not logged in.');
```
but it always becomes this:
```dart
(auth.isSignedIn) ? silentLoginEvent() : log.i('Firebase instance created. Not logged in.');
```

If that is not the plan, I definitely understand and will keep looking, perhaps one day I will come across one.

Thanks,
-MH

**Comment by levelrin** [comment]
Good question. I have not thought of that.
I think people will create their own formatter anyways if we don't have a configurable formatter.
So having a customizable option might not be a bad idea.
It will probably take a long time to develop that far.
In the meantime, I suggest you to keep looking around :)

**Comment by MostHated** [comment]
Understood. I appreciate you taking the time to reply. I wish you luck in the project, I will be sure to keep an eye on it. 👍
